services:
  spring:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    image: sft-backend
    container_name: spring
    ports:
      - "8081:8081"
    volumes:
      - ./Back-End:/app
    networks:
      - app-network

  react:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    image: sft-frontend
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./Front-End:/app
    networks:
      - app-network
