services:
  spring:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    image: sft-backend
    container_name: spring
    restart: always
    ports:
      - "8082:8082"
    networks:
      - app-network

  react:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    image: sft-frontend
    container_name: react
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge